name: eventyay

services:
  postgres:
    image: postgis/postgis:15-3.5
    container_name: eventyay-postgres
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${VOLUMES_DIR}/postgres/data:/var/lib/postgresql/data
      - ${CONFIG_DIR}/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      # the following where in the original eventyay-video docker-compose.yaml
      # but I am not sure why they are necessary
      # POSTGRES_INITDB_ARGS: --auth-host=md5
      # POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ey_ticket_db,ey_talk_db,ey_video_db
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U ${POSTGRES_USER} -d ey_talk_db']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: eventyay-redis
    restart: unless-stopped
    network_mode: host
    command: --port 6379
    volumes:
      - rd:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  # eventyay-video uses two different redis servers, the first is
  # for celery, while the second for whatever
  redis1:
    image: redis:latest
    container_name: eventyay-redis1
    restart: unless-stopped
    network_mode: host
    command: --port 6380
    volumes:
      - rd1:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  nginx: # this is nginx + certbot, see https://github.com/JonasAlfredsson/docker-nginx-certbot
    restart: always
    image: jonasal/nginx-certbot:latest
    container_name: eventyay-nginx
    network_mode: host
    volumes:
      - ${CONFIG_DIR}/nginx/letsencrypt:/etc/letsencrypt
      - ${CONFIG_DIR}/nginx/user_conf/:/etc/nginx/user_conf.d/:ro
      - ${VOLUMES_DIR}/talk/data:/talk-data
      - ${VOLUMES_DIR}/ticket/data:/ticket-data
    env_file:
      - ${CONFIG_DIR}/nginx/nginx-certbot.env
    environment: # only those overriding the defaults in the nginx-certbot.env above
      - CERTBOT_EMAIL=some@email.org
      # - CERTBOT_AUTHENTICATOR=dns-cloudflare
      # make sure we run against local auto-generated CA
      - USE_LOCAL_CA=1

# volumes for redis that can be dropped and don't need moving
volumes:
  rd:
  rd1:
